services:
  typesense:
    image: typesense/typesense:29.0
    restart: unless-stopped
    ports:
      - "${TYPESENSE_PORT}:8108"
    volumes:
      - typesense-data:/data
    env_file:
      - .env
    command: '--data-dir /data --api-key="${TYPESENSE_API_KEY}" --enable-cors'

volumes:
  typesense-data:
